corona/corona/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('', include('symptoms.urls')),
    path('admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

corona/symptoms/urls.py
from django.urls import path

from . import views

app_name = 'SymptomsReports'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /SymptomsReports/5/
    path('SymptomsReports/<int:symptomreport_id>/', views.detail, name='detail'),
    # ex: SymptomsReports/report/
    path('report/', views.report, name='report'),
    # for post
    path('SymptomsReports/submitreport/',
         views.reportsubmit, name='reportsubmit'),
    path('api/reports/municipalities/<int:municipality_code>/', views.list_municipality_data,
         name='list_municipality_data'),
    path('api/reports/municipalities', views.list_municipality_data,
         name='list_municipality_data')
]

corona/symptoms/forms.py
import logging

from django import forms
from django.utils import timezone
from django.forms import ModelForm, CharField, MultipleChoiceField, DateTimeField, IntegerField
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField
from .models import SymptomsReport, Symptom, PostCodeArea
from . import constants


# Get an instance of a logger
logger = logging.getLogger(__name__)


class SymptomsReportForm(ModelForm):

    captcha = CaptchaField()

    postal_code = CharField(
        min_length=5,
        max_length=5,
        required=True,
        strip=True,
        label=_('formFieldPostalCode'),
    )

    symptoms = MultipleChoiceField(
        choices=Symptom.SymptomName.choices,
        widget=forms.CheckboxSelectMultiple,
        label=_('formFieldSymptoms'),
    )

    # Override to enforce range [min, max] in frontend
    duration = IntegerField(
        required=False,
        label=_('formFieldDuration'),
        min_value=constants.MIN_DURATION,
        max_value=constants.MAX_DURATION
    )

    # Override to enforce range [min, max] in frontend
    size_of_household = IntegerField(
        required=False,
        label=_('formFieldSizeOfHousehold'),
        min_value=constants.MIN_SIZE_OF_HOUSEHOLD,
        max_value=constants.MAX_SIZE_OF_HOUSEHOLD)

    fill_start_time = DateTimeField(
        initial=timezone.now(),
        required=False,
        widget=forms.HiddenInput(),
    )

    field_order = ['postal_code', 'symptoms', 'tested_for_covid19', 'duration', 'size_of_household', 'age', 'sex']

    def clean_postal_code(self):
        data = self.cleaned_data.get('postal_code')

        if data is None:
            raise ValidationError(_("formErrorNoPostalCode"))

        try:
            post_code_area = PostCodeArea.objects.get(postal_code=data)
            logger.debug("Found matching post code area: {} -> {}".format(data, post_code_area))
        except PostCodeArea.DoesNotExist:
            raise ValidationError(_("formErrorInvalidPostalCode"))

        return data

    def clean_symptoms(self):
        data = self.cleaned_data.get('symptoms', [])

        if len(data) == 0:
            raise ValidationError(_("formErrorNoSymptoms"))

        if 'NONE' in data and len(data) > 1:
            raise ValidationError(_("formErrorNoSymptomsCombined"))

        return data

    class Meta:
        model = SymptomsReport
        exclude = ['fill_start_time', 'post_code_area', 'user_cookie', 'created_at', 'fill_time_sec',
                   'user_cookie_hash', 'client_user_agent_hash', 'client_ip_hash', 'client_geoip_country_code']
        required = ['postal_code', 'symptoms']

corona/symptoms/views.py
import json
import logging
import uuid

from typing import Union

from waffle import flag_is_active

from django.core.serializers.json import DjangoJSONEncoder
from django.core.signing import BadSignature
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import force_text
from django.utils.functional import Promise
from django.contrib.gis.geoip2 import GeoIP2
from django.conf import settings

from ipware import get_client_ip

from . import constants
from .utils import _get_hashed_value
from .forms import SymptomsReportForm
from .models import PostCodeArea, Symptom, SymptomsReport


# Get an instance of a logger
logger = logging.getLogger(__name__)


_GEO_IP2 = GeoIP2()
_POSTAL_CODE_TO_SAFE_POSTAL_CODE = {}


class GetTextLazyEncoder(DjangoJSONEncoder):
    def default(self, obj):
        if isinstance(obj, Promise):
            return force_text(obj)
        return super(GetTextLazyEncoder, self).default(obj)


def index(request):
    template = loader.get_template('SymptomsReport/index.html')
    context = {
        'symptom_report_json': json.dumps(_municipality_symptom_report()),
        'translations_json': json.dumps(_municipality_symptom_report_translations(), cls=GetTextLazyEncoder),
    }
    return HttpResponse(template.render(context, request))


def detail(request, symptomreport_id):
    return HttpResponse("You're looking at SymptomReport %s. Symptom was" % symptomreport_id)


def report(request):
    previous_symptoms_report = None

    try:
        user_cookie = request.get_signed_cookie(constants.USER_COOKIE_NAME)
        if user_cookie:
            previous_symptoms_report = _get_previous_user_symptoms_report(user_cookie)
    except (KeyError, BadSignature) as e:
        logger.warning("Failed to get user cookie: {}".format(e))

    data = None

    if previous_symptoms_report:
        logger.info("Found latest symptoms report for user: {}. Report: {}"
                    .format(previous_symptoms_report.user_cookie, previous_symptoms_report))

        # Check that the cooldown has passed if not redirect the user to the cooldown page
        if not _reporting_cooldown_passed(request ,previous_symptoms_report):
            template = loader.get_template('SymptomsReport/cooldown.html')
            delta = timezone.now() - previous_symptoms_report.created_at
            context = {
                'cooldown_period_hours': int(constants.SYMPTOM_REPORT_COOLDOWN_SEC/(60*60)),
                'cooldown_remaining_hours': int(round((constants.SYMPTOM_REPORT_COOLDOWN_SEC-delta.total_seconds())/(60*60)))
            }
            return HttpResponse(template.render(context, request))

        # If cooldown has passed do the user a favour and prepopulate the fields with previous responses
        symptoms = list(previous_symptoms_report.symptoms.all())
        symptoms = [s.name for s in symptoms]
        data = {
            'postal_code': previous_symptoms_report.post_code_area.postal_code,
            'symptoms': symptoms,
            'duration': previous_symptoms_report.duration,
            'age': previous_symptoms_report.age,
            'sex': previous_symptoms_report.sex,
        }

    # TODO Plz fix urls and namespaces
    template = loader.get_template('SymptomsReport/report.html')
    context = {'form': SymptomsReportForm(initial=data)}
    return HttpResponse(template.render(context, request))


def reportsubmit(request):
    form = SymptomsReportForm(request.POST)

    if not form.is_valid():
        logger.warning("Form failed validation: {}".format(form.errors))
        return render(request, 'SymptomsReport/report.html', {'form': form})

    response = HttpResponseRedirect(reverse('SymptomsReports:index'))

    try:
        # If the user cookie was set this is an existing user
        user_cookie = request.get_signed_cookie(constants.USER_COOKIE_NAME)
        user_cookie_hash = None

        if user_cookie:
            # Check if the user has already reported - if they have check that the cooldown period has passed
            logger.info("Found existing signed user cookie: {}".format(user_cookie))
            previous_symptoms_report = _get_previous_user_symptoms_report(user_cookie)

            if previous_symptoms_report:
                user_cookie_hash = previous_symptoms_report.user_cookie_hash

                if not _reporting_cooldown_passed(request, previous_symptoms_report):
                    return response
            else:
                user_cookie_hash = None
    except BadSignature as e:
        logger.error("Signed user cookie signature failed: {}".format(e))
        user_cookie = None
        user_cookie_hash = None
    except KeyError:
        logger.info("Could not find existing signed user cookie")
        user_cookie = None
        user_cookie_hash = None

    # If there was no existing user cookie or retrieving the cookie failed:
    # set a new user cookie so we know the user has answered already
    if not user_cookie:
        user_cookie = uuid.uuid4()
        logger.info("Created new signed user cookie: {}".format(user_cookie))
        response.set_signed_cookie(
            constants.USER_COOKIE_NAME, str(user_cookie))

    # If the user cookie hash doesn't exist create it
    if not user_cookie_hash:
        user_cookie_hash = _get_hashed_value(str(user_cookie), settings.HASHING_SALT)

    symptoms = form.cleaned_data.get('symptoms')
    postal_code = form.cleaned_data.get('postal_code')
    tested_for_covid19 = form.cleaned_data.get('tested_for_covid19')
    size_of_household = form.cleaned_data.get('size_of_household')
    sex = form.cleaned_data.get('sex')
    duration = form.cleaned_data.get('duration')
    age = form.cleaned_data.get('age')
    post_code_area = _get_safe_post_code_area(postal_code)
    created_at = timezone.now()

    # Get client User-Agent, IP and country according to GeoIP
    # Hash the User-Agent and IP for privacy, - save the hashes and the country name with the data.
    # This way we can attempt to sanitize trolls easier from the data.
    client_user_agent_hash = _get_hashed_value(_get_client_user_agent(request), settings.HASHING_SALT)
    client_ip_hash = _get_hashed_value(_get_client_ip(request), settings.HASHING_SALT)
    client_geoip_country_code = _get_client_country_code(request)
    fill_start_time = form.cleaned_data.get('fill_start_time')

    if fill_start_time:
        fill_time_sec = int((created_at - fill_start_time).total_seconds())
    else:
        fill_time_sec = None

    symptoms_report = SymptomsReport(
        post_code_area=post_code_area,
        tested_for_covid19=tested_for_covid19,
        size_of_household=size_of_household,
        age=age,
        sex=sex,
        duration=duration,
        created_at=created_at,
        user_cookie=user_cookie,
        fill_time_sec=fill_time_sec,
        user_cookie_hash=user_cookie_hash,
        client_user_agent_hash=client_user_agent_hash,
        client_ip_hash=client_ip_hash,
        client_geoip_country_code=client_geoip_country_code)
    symptoms_report.save()

    for symptom_name in symptoms:
        symptom = Symptom(
            name=symptom_name,
            symptoms_report=symptoms_report
        )
        symptom.save()

    return response


def list_municipality_data(request, municipality_code=None):
    report = _municipality_symptom_report(municipality_code=municipality_code)

    return JsonResponse({
        "report": report,
    })


def _municipality_symptom_report(municipality_code=None):
    symptom_counts_by_municipality = Symptom.objects\
        .values('symptoms_report__post_code_area__municipality__code', 'name')\
        .annotate(count=Count('name'))
    symptom_reports_counts_by_municipality = SymptomsReport.objects\
        .values('post_code_area__municipality__code')\
        .annotate(count=Count('post_code_area__municipality__code'))

    if municipality_code is not None:
        symptom_counts_by_municipality = symptom_counts_by_municipality.filter(
            symptoms_report__post_code_area__municipality__code=municipality_code)
        symptom_reports_counts_by_municipality = symptom_counts_by_municipality.filter(
            post_code_area__municipality__code=municipality_code)

    report = {}
    for record in symptom_counts_by_municipality:
        key = record["symptoms_report__post_code_area__municipality__code"]
        val = report.get(key, {"reports": {}, "symptoms": {}})
        val["symptoms"][record["name"]] = record["count"]
        report[key] = val
    for record in symptom_reports_counts_by_municipality:
        key = record["post_code_area__municipality__code"]
        val = report.get(key, {"reports": {}, "symptoms": {}})
        val["reports"]["count"] = record["count"]
        report[key] = val

    logger.debug(symptom_counts_by_municipality.query)
    logger.debug(symptom_reports_counts_by_municipality.query)

    return report


def _municipality_symptom_report_translations():
    return dict(Symptom.SymptomName.choices)


def _get_previous_user_symptoms_report(user_cookie: str) -> Union[SymptomsReport, None]:
    if user_cookie:
        try:
            previous_symptoms_report = SymptomsReport.objects.filter(user_cookie=user_cookie).order_by('-created_at')[0]
            logger.info("Found previous symptoms report for user: {}. Report: {}"
                        .format(user_cookie, previous_symptoms_report))
            return previous_symptoms_report
        except Exception as e:
            logger.error("Failed to get previous symptoms report for user: {}. Error: {}"
                         .format(user_cookie, e))
    return None


def _reporting_cooldown_passed(request, report: SymptomsReport) -> bool:
    if not flag_is_active(request, 'USE_SYMPTOM_REPORT_COOLDOWN'):

corona/symptoms/templates/SymptomsReport/cooldown.html
{% load static %}
{% load i18n %}

<style>
    body {
        background-color: rgb(202, 227, 194);
        font-family: Arial;
        margin: 30px;
    }

    .card {
        margin-top: 15px;
        border: 2px solid #2d5520;
        width: calc(100% - 54px);
        padding: 25px;
        color: #2d5520;
        font-size: 22px;
        border-radius: 5px;
        display: table;
        text-align: center;
        background-color: #cae3c2
    }

    #frontpage-link {
        margin-top: 15px;
        background-color: #2d5520;
        width: calc(100% - 50px);
        padding: 25px;
        color: #cae3c2;
        font-size: 17px;
        border-radius: 5px;
        display: table;
        transition-timing-function: ease-out;
        transition: transform .2s
    }

    .link-icon {
        text-align: right;
    }

    .light {
        color: #7d9e73;
        font-size: 13px;
    }

    a {
        color: #2d5520;
        text-decoration: none;
        border-bottom: 1px solid #2d5520
    }

    .card-value {
        display: block;
        margin-top: 5px;
        font-size: 37px;
        font-weight: 700
    }
</style>

<a href="/">
    <div class="card" id="frontpage-link">
        <div class="report-link-text">
            {% trans "uiBackToFrontpage" %}<br>
            <i class="light">{% trans "uiBackToFrontpageDescription" %}</i>
        </div>
        <div class="link-icon">
            <img src="{%static 'open.svg' %}" />
        </div>
    </div>
</a>

<div class="card">
    <p class="card-value">
        {% trans "uiThankYouForReporting" %}
    </p>
    <p>
        {% blocktrans %}
        You should only report your symptoms once in {{ cooldown_period_hours }} hours.
        You still have {{ cooldown_remaining_hours }} hours until the next reporting period.
        {% endblocktrans %}
    </p>
</div>

corona/symptoms/templates/SymptomsReport/index.html
{% load static %}
{% load i18n %}

<script src="https://d3js.org/d3.v3.min.js"></script>
<script src="https://d3js.org/d3-geo.v1.min.js"></script>
<script src="https://d3js.org/topojson.v1.min.js"></script>
<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />

<style>
    body {
        background-color: rgb(202, 227, 194);
        font-family: Arial;
        margin: 30px;
    }

    path {
        fill: #000;
        stroke: #fff;
        stroke-width: .5px;
    }

    path:hover {
        fill: #fff;
    }

    .card {
        margin-top: 15px;
        border: 2px solid #2d5520;
        width: calc(100% - 54px);
        padding: 25px;
        color: #2d5520;
        font-size: 22px;
        border-radius: 5px;
        display: table;
        text-align: center;
        background-color: #cae3c2
    }

    .card-value {
        display: block;
        margin-top: 5px;
        font-size: 37px;
        font-weight: 700
    }

    #report-link {
        margin-top: 15px;
        background-color: #2d5520;
        width: calc(100% - 50px);
        padding: 25px;
        color: #cae3c2;
        font-size: 17px;
        border-radius: 5px;
        display: table;
        transition-timing-function: ease-out;
        transition: transform .2s
    }

    .link-icon {
        text-align: right;
    }

    table {
        margin-top: 15px;
        margin-left: auto;
        margin-right: auto;
    }

    a {
        color: #2d5520;
        text-decoration: none;
        border-bottom: 1px solid #2d5520
    }

    .report-link-text {
        display: table-cell;
        width: calc(100% - 35px);
    }

    .light {
        color: #7d9e73;
        font-size: 13px;
    }

    .svg-container {
        display: inline-block;
        position: relative;
        width: 100%;
        padding-bottom: 100%;
        vertical-align: middle;
        overflow: hidden;
    }

    .svg-content {
        display: inline-block;
        position: absolute;
        top: 0;
        left: 0;
    }
</style>

<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
            {{ language.name_local }} ({{ language.code }})
        </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go">
</form>

<a href="/report/">
    <div class="card" id="report-link">
        <div class="link-icon">
            <img src="{%static 'open.svg' %}" />
        </div>
        <div class="report-link-text">
            <h2>{% trans "uiReportSymptoms" %}</h2><br>
            <i class="light">{% trans "uiReportSymptomsDescription" %}</i>
        </div>
        <div class="link-icon">
            <img src="{%static 'open.svg' %}" />
        </div>
    </div>
</a>

<div class="card" id="total-reports">
    <span class="card-title">{% trans "uiReportsTotal" %}</span><br />
    <span class="card-value" id="reports-in-total-value">{% trans "uiReportsTotalZero" %}</span>
</div>

<div class="card" id="map-container">
    <div id='map' data-report="{{ symptom_report_json }}" data-i18n="{{ translations_json }}"></div>
</div>
</div>

<div class="card" id="selection-statistics">
    <span class="card-title" id="selected-area-name">{% trans "uiReportCountry" %}</span>
    <span class="card-value" id="selected-area-total-reports"></span>
    <div id="selection-statistics-table-container"></div>
</div>

<script>
    var tabulate = function ({ parent, municipality, translations, data }) {
        var table = parent.append("table");
        var thead = table.append("thead");
        var tbody = table.append("tbody");

        document.getElementById('selected-area-name').innerText = municipality;
        document.getElementById('selected-area-total-reports').innerText = data.reports.count;

        // create a row for each object in the data
        var rows = tbody.selectAll("tr")
            .data(Object.keys(data.symptoms))
            .enter()
            .append("tr");

        var cells = rows.selectAll("td")
            .data(function (symptom) {
                return [{ symptom: symptom, count: data.symptoms[symptom], total: data.reports.count }];
            });

        cells.enter()
            .append("td")
            .html("<img src=\"{%static 'bullet.svg' %}\"/>");

        cells.enter()
            .append("td")
            .text(function (d) { return translations[d.symptom]; });

        cells.enter()
            .append("td")
            .text(function (d) { return d.count + " / " + d.total; });

        return table;
    }

    var renderMap = function ({ mapElem, symptomsTable, geojson, reportData }) {
        var mapNode = mapElem.node();
        var svg = mapElem
            .append("svg")
            .attr("width", "100%")
            .attr("height", 500);
        var projection = d3.geoMercator()
            .center([61.9241104, 25.7481518])
            .fitSize([mapNode.clientWidth, mapNode.clientHeight], geojson);
        var path = d3.geoPath(projection);

        var updateStatistics = function(d) {
            if (symptomsTable) {
                symptomsTable.remove();
            }
            symptomsTable = tabulate({
                parent: div,
                translations: translationData,
                municipality: d.properties.name,
                data: reportData[parseInt(d.properties.code)] || { symptoms: { NONE: 0 }, reports: { count: 0 } }
            });
        };

        svg.selectAll("path")
            .data(geojson.features)
            .enter()
            .append("path")
            .attr("d", path)
            .style("fill", function (d) {
                var data = reportData[parseInt(d.properties.code)] || { symptoms: { NONE: 1 }, reports: { count: 1 } } // default to math: (1 - 1/1) * 255 = 0
                var healthy = data.symptoms.NONE || 0
                var total = data.reports.count
                return "rgb(" + Math.floor((1 - (healthy / total)) * 255) + ",0,0)";
            })
            .on("click", function (d) {
                updateStatistics(d);
            })
            .on("mouseover", function (d) {
                updateStatistics(d);
            });

        return svg;
    }
    var translationData = JSON.parse(document.getElementById("map").dataset.i18n);
    var reportData = JSON.parse(document.getElementById("map").dataset.report);
    var aggregateReportData = { reports: { count: 0 }, symptoms: {} }

    Object.keys(reportData).forEach(function (key) {
        var report = reportData[key]
        aggregateReportData.reports.count += report.reports.count

        Object.keys(report.symptoms).forEach(function (skey) {
            aggregateReportData.symptoms[skey] = aggregateReportData.symptoms[skey] || 0
            if (report.symptoms[skey]) {
                aggregateReportData.symptoms[skey] += report.symptoms[skey]
            }
        })
    })

    document.getElementById('reports-in-total-value').innerText = aggregateReportData.reports.count;
    document.getElementById('selected-area-total-reports').innerText = aggregateReportData.reports.count;

    var div = d3.select("#selection-statistics-table-container");
    var symptomsTable = tabulate({
        parent: div,
        translations: translationData,
        municipality: "{% trans 'uiReportCountry' %}",
        data: aggregateReportData,
    });

    d3.json("{%static 'finland-municipalities-topojson.json' %}", function (error, topology) {
        if (error) throw error;

        var geojson = topojson.feature(topology, topology.objects.kuntarajat);
        var mapElem = d3.select("#map");
        var render = function () { return renderMap({ mapElem, symptomsTable, geojson, reportData }) }

        var svg = render();
        window.addEventListener('resize', () => {
            svg.remove();
            svg = render()
        })
    });
</script>

corona/symptoms/templates/SymptomsReport/report.html
{% load i18n %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!-- # Cookie consent, can be customized here: https://www.osano.com/cookieconsent/download/ -->
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
<script>
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#1d8a8a"
    },
    "button": {
      "background": "#62ffaa"
    }
  }
});
</script>

<!-- from https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag -->
<meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=3.0, minimum-scale=0.86">

<style>
    body {
        background-color: rgb(202, 227, 194);
        font-family: Arial;
        margin: 30px;
    }

    .invalid-feedback {
        display: block;
        font-size: 100%;
        font-weight: bold;
    }

    div.required-field > label:after {
        color: red;
        content: " *";
    }

    .btn {
        width: 100%;
        height: 50px;
    }
</style>

<h1>{% trans "uiReportSyptomsFormHeader" %}</h1>

<form action="{% url 'SymptomsReports:reportsubmit' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
        {% bootstrap_field field required_css_class='required-field' %}
    {% endfor %}

    {% buttons %}
    <button type="submit" class="btn btn-primary">{% trans "uiReportSymptomsFormCTA" %}</button>
    {% endbuttons %}
</form>

corona/symptoms/templates/SymptomsReport/thankyou.html
Thank you for answering!